apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: devops-practical
spec:
  type: NodePort
  selector:
    app: devops-practical-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
