apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - mongo-pv.yaml
  - mongo-pvc.yaml
  - mongo-statefulset.yaml
  - mongo-service.yaml
  - app-configmap.yaml
  - app-deployment.yaml
  - app-service.yaml
  - app-hpa.yaml
